services:
  nextcloud-aio-mastercontainer:
    image: 'nextcloud/all-in-one:latest'
    restart: always
    container_name: nextcloud-aio-mastercontainer
    volumes:
      - 'nextcloud_aio_mastercontainer:/mnt/docker-aio-config'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/mnt/jays-data/nextcloud-aio/data:/mnt/ncdata:rw'
    ports:
      - '11000:8080'
    environment:
      - APACHE_PORT=${APACHE_PORT:-11000}
      - APACHE_IP_BINDING=${APACHE_IP_BINDING:-127.0.0.1}
      - SKIP_DOMAIN_VALIDATION=${SKIP_DOMAIN_VALIDATION:-true}
      - NEXTCLOUD_DATADIR=${NEXTCLOUD_DATADIR:-/mnt/ncdata}
      - AIO_TOKEN=${AIO_TOKEN}
      - COOLIFY_CONTAINER_NAME=nextcloud-aio-mastercontainer
    networks:
      - coolify
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - traefik.http.routers.nextcloud-aio.rule=Host(`skygod.psimatic.io`)
      - traefik.http.routers.nextcloud-aio.tls.certresolver=letsencrypt
      - traefik.http.services.nextcloud-aio.loadbalancer.server.port=8080
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
networks:
  coolify:
    external: true
